export interface QuizComponentsText {
  // QuizDisplay.tsx
  sections: string;
  questions: string;
  sourceFiles: string;
  retakeQuiz: string;
  evaluateAnswers: string;
  showResults: string;

  // QuizDisplayError.tsx
  generationFailedSuffix: string;
  quizGenerationFailed: string;
  quizNotValid: string;
  regenerateQuiz: string;

  // QuizDIsplayRezultateGrila.tsx
  wrongAnswers: string;
  wrongAnswerCorrect: string;
  noWrongAnswers: string;
  correctAnswers: string;
  correctAnswer: string;
  noCorrectAnswers: string;
  conclusion: string;
  fileLabel: string;
  total: string;

  // ItemIntrebare.tsx
  answerQuestionPlaceholder: string;
  mustSelectAnswer: string;
}

const supportedLanguages = [
  "English",
  "Mandarin Chinese",
  "Romanian",
  "Spanish",
  "Modern Standard Arabic",
  "French",
  "Russian",
  "German",
  "Japanese",
  "Vietnamese",
  "Turkish",
] as const;

export type QuizComponentsLanguage = (typeof supportedLanguages)[number];

const quizComponentsTexts: Record<QuizComponentsLanguage, QuizComponentsText> = {
  English: {
    // QuizDisplay.tsx
    sections: "sections",
    questions: "questions",
    sourceFiles: "source files",
    retakeQuiz: "Retake Quiz",
    evaluateAnswers: "Evaluate Answers",
    showResults: "Show Results",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - Generation Failed",
    quizGenerationFailed: "Quiz Generation Failed",
    quizNotValid: "The Quiz Generated By The Ai Is Not Valid",
    regenerateQuiz: "Regenerate Quiz",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "Wrong Answers",
    wrongAnswerCorrect: "Wrong answer (Correct:",
    noWrongAnswers: "No wrong answers",
    correctAnswers: "Correct Answers",
    correctAnswer: "Correct answer",
    noCorrectAnswers: "No correct answers",
    conclusion: "Conclusion",
    fileLabel: "File:",
    total: "Total",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "answer the question",
    mustSelectAnswer: "Must select an answer for this question",
  },
  "Mandarin Chinese": {
    // QuizDisplay.tsx
    sections: "部分",
    questions: "问题",
    sourceFiles: "源文件",
    retakeQuiz: "重新参加测验",
    evaluateAnswers: "评估答案",
    showResults: "显示结果",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - 生成失败",
    quizGenerationFailed: "测验生成失败",
    quizNotValid: "AI生成的测验无效",
    regenerateQuiz: "重新生成测验",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "错误答案",
    wrongAnswerCorrect: "错误答案（正确答案：",
    noWrongAnswers: "没有错误答案",
    correctAnswers: "正确答案",
    correctAnswer: "正确答案",
    noCorrectAnswers: "没有正确答案",
    conclusion: "结论",
    fileLabel: "文件：",
    total: "总计",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "回答问题",
    mustSelectAnswer: "必须为此问题选择一个答案",
  },
  Romanian: {
    // QuizDisplay.tsx
    sections: "secțiuni",
    questions: "întrebări",
    sourceFiles: "fișiere sursă",
    retakeQuiz: "Reluare Quiz",
    evaluateAnswers: "Evaluează Răspunsurile",
    showResults: "Afișează Rezultatele",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - Generarea a Eșuat",
    quizGenerationFailed: "Generarea Quiz-ului a Eșuat",
    quizNotValid: "Quiz-ul Generat de AI Nu este Valid",
    regenerateQuiz: "Regenerare Quiz",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "Răspunsuri Greșite",
    wrongAnswerCorrect: "Răspuns greșit (Corect:",
    noWrongAnswers: "Niciun răspuns greșit",
    correctAnswers: "Răspunsuri Corecte",
    correctAnswer: "Răspuns corect",
    noCorrectAnswers: "Niciun răspuns corect",
    conclusion: "Concluzie",
    fileLabel: "Fișier:",
    total: "Total",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "răspunde la întrebare",
    mustSelectAnswer: "Trebuie să selectați un răspuns pentru această întrebare",
  },
  Spanish: {
    // QuizDisplay.tsx
    sections: "secciones",
    questions: "preguntas",
    sourceFiles: "archivos fuente",
    retakeQuiz: "Rehacer Cuestionario",
    evaluateAnswers: "Evaluar Respuestas",
    showResults: "Mostrar Resultados",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - Generación Fallida",
    quizGenerationFailed: "Generación del Cuestionario Fallida",
    quizNotValid: "El Cuestionario Generado por la IA no es Válido",
    regenerateQuiz: "Regenerar Cuestionario",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "Respuestas Incorrectas",
    wrongAnswerCorrect: "Respuesta incorrecta (Correcta:",
    noWrongAnswers: "Sin respuestas incorrectas",
    correctAnswers: "Respuestas Correctas",
    correctAnswer: "Respuesta correcta",
    noCorrectAnswers: "Sin respuestas correctas",
    conclusion: "Conclusión",
    fileLabel: "Archivo:",
    total: "Total",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "responde a la pregunta",
    mustSelectAnswer: "Debes seleccionar una respuesta para esta pregunta",
  },
  "Modern Standard Arabic": {
    // QuizDisplay.tsx
    sections: "الأقسام",
    questions: "الأسئلة",
    sourceFiles: "ملفات المصدر",
    retakeQuiz: "إعادة الاختبار",
    evaluateAnswers: "تقييم الإجابات",
    showResults: "عرض النتائج",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - فشل الإنشاء",
    quizGenerationFailed: "فشل إنشاء الاختبار",
    quizNotValid: "الاختبار المولد بواسطة الذكاء الاصطناعي غير صالح",
    regenerateQuiz: "إعادة إنشاء الاختبار",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "إجابات خاطئة",
    wrongAnswerCorrect: "إجابة خاطئة (الصحيحة:",
    noWrongAnswers: "لا توجد إجابات خاطئة",
    correctAnswers: "إجابات صحيحة",
    correctAnswer: "إجابة صحيحة",
    noCorrectAnswers: "لا توجد إجابات صحيحة",
    conclusion: "الاستنتاج",
    fileLabel: "ملف:",
    total: "المجموع",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "أجب على السؤال",
    mustSelectAnswer: "يجب اختيار إجابة لهذا السؤال",
  },
  French: {
    // QuizDisplay.tsx
    sections: "sections",
    questions: "questions",
    sourceFiles: "fichiers sources",
    retakeQuiz: "Repasser le Quiz",
    evaluateAnswers: "Évaluer les Réponses",
    showResults: "Afficher les Résultats",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - Échec de la Génération",
    quizGenerationFailed: "Génération du Quiz Échouée",
    quizNotValid: "Le Quiz Généré par l'IA n'est Pas Valide",
    regenerateQuiz: "Régénérer le Quiz",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "Mauvaises Réponses",
    wrongAnswerCorrect: "Mauvaise réponse (Correcte :",
    noWrongAnswers: "Aucune mauvaise réponse",
    correctAnswers: "Bonnes Réponses",
    correctAnswer: "Bonne réponse",
    noCorrectAnswers: "Aucune bonne réponse",
    conclusion: "Conclusion",
    fileLabel: "Fichier :",
    total: "Total",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "répondez à la question",
    mustSelectAnswer: "Vous devez sélectionner une réponse pour cette question",
  },
  Russian: {
    // QuizDisplay.tsx
    sections: "разделы",
    questions: "вопросы",
    sourceFiles: "исходных файлов",
    retakeQuiz: "Пересдать Тест",
    evaluateAnswers: "Оценить Ответы",
    showResults: "Показать Результаты",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} — Ошибка Генерации",
    quizGenerationFailed: "Генерация Теста Не Удалась",
    quizNotValid: "Тест, Сгенерированный ИИ, Недействителен",
    regenerateQuiz: "Регенерировать Тест",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "Неправильные Ответы",
    wrongAnswerCorrect: "Неправильный ответ (Правильный:",
    noWrongAnswers: "Нет неправильных ответов",
    correctAnswers: "Правильные Ответы",
    correctAnswer: "Правильный ответ",
    noCorrectAnswers: "Нет правильных ответов",
    conclusion: "Заключение",
    fileLabel: "Файл:",
    total: "Итого",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "ответить на вопрос",
    mustSelectAnswer: "Необходимо выбрать ответ для этого вопроса",
  },
  German: {
    // QuizDisplay.tsx
    sections: "Abschnitte",
    questions: "Fragen",
    sourceFiles: "Quelldateien",
    retakeQuiz: "Quiz Wiederholen",
    evaluateAnswers: "Antworten Bewerten",
    showResults: "Ergebnisse Anzeigen",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} – Generierung Fehlgeschlagen",
    quizGenerationFailed: "Quiz-Generierung Fehlgeschlagen",
    quizNotValid: "Der KI-generierte Quiz ist Ungültig",
    regenerateQuiz: "Quiz Neu Generieren",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "Falsche Antworten",
    wrongAnswerCorrect: "Falsche Antwort (Richtig:",
    noWrongAnswers: "Keine falschen Antworten",
    correctAnswers: "Korrekte Antworten",
    correctAnswer: "Korrekte Antwort",
    noCorrectAnswers: "Keine korrekten Antworten",
    conclusion: "Fazit",
    fileLabel: "Datei:",
    total: "Gesamt",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "stelle die Frage",
    mustSelectAnswer: "Müssen Sie eine Antwort für diese Frage auswählen",
  },
  Japanese: {
    // QuizDisplay.tsx
    sections: "セクション",
    questions: "質問",
    sourceFiles: "ソースファイル",
    retakeQuiz: "再挑戦",
    evaluateAnswers: "回答を評価",
    showResults: "結果を表示",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - 生成に失敗しました",
    quizGenerationFailed: "クイズの生成に失敗しました",
    quizNotValid: "AIが生成したクイズは有効ではありません",
    regenerateQuiz: "クイズを再生成",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "不正解",
    wrongAnswerCorrect: "不正解（正解：",
    noWrongAnswers: "不正解はありません",
    correctAnswers: "正解",
    correctAnswer: "正解",
    noCorrectAnswers: "正解はありません",
    conclusion: "結論",
    fileLabel: "ファイル：",
    total: "合計",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "質問に答える",
    mustSelectAnswer: "この質問の回答を選択する必要があります",
  },
  Vietnamese: {
    // QuizDisplay.tsx
    sections: "phần",
    questions: "câu hỏi",
    sourceFiles: "tệp nguồn",
    retakeQuiz: "Làm Lại Quiz",
    evaluateAnswers: "Đánh Giá Câu Trả Lời",
    showResults: "Hiển Thị Kết Quả",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - Tạo Thất Bại",
    quizGenerationFailed: "Tạo Quiz Thất Bại",
    quizNotValid: "Quiz do AI tạo không hợp lệ",
    regenerateQuiz: "Tạo Lại Quiz",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "Câu Trả Lời Sai",
    wrongAnswerCorrect: "Trả lời sai (Đúng:",
    noWrongAnswers: "Không có câu trả lời sai",
    correctAnswers: "Câu Trả Lời Đúng",
    correctAnswer: "Câu trả lời đúng",
    noCorrectAnswers: "Không có câu trả lời đúng",
    conclusion: "Kết Luận",
    fileLabel: "Tệp:",
    total: "Tổng Cộng",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "trả lời câu hỏi",
    mustSelectAnswer: "Phải chọn một câu trả lời cho câu hỏi này",
  },
  Turkish: {
    // QuizDisplay.tsx
    sections: "bölümler",
    questions: "sorular",
    sourceFiles: "kaynak dosyalar",
    retakeQuiz: "Tekrar Çöz",
    evaluateAnswers: "Yanıtları Değerlendir",
    showResults: "Sonuçları Göster",

    // QuizDisplayError.tsx
    generationFailedSuffix: "{quizName} - Oluşturma Başarısız",
    quizGenerationFailed: "Quiz Oluşturma Başarısız Oldu",
    quizNotValid: "AI Tarafından Oluşturulan Quiz Geçerli Değil",
    regenerateQuiz: "Quiz'i Yeniden Oluştur",

    // QuizDIsplayRezultateGrila.tsx
    wrongAnswers: "Yanlış Cevaplar",
    wrongAnswerCorrect: "Yanlış cevap (Doğru:",
    noWrongAnswers: "Yanlış cevap yok",
    correctAnswers: "Doğru Cevaplar",
    correctAnswer: "Doğru cevap",
    noCorrectAnswers: "Doğru cevap yok",
    conclusion: "Sonuç",
    fileLabel: "Dosya:",
    total: "Toplam",

    // ItemIntrebare.tsx
    answerQuestionPlaceholder: "soruyu yanıtla",
    mustSelectAnswer: "Bu soru için bir yanıt seçmelisiniz",
  },
};

export function getQuizComponentsText(language: string): QuizComponentsText {
  return quizComponentsTexts[language as QuizComponentsLanguage] ?? quizComponentsTexts["English"];
}

export { supportedLanguages };

export const quizComponentsTextsArray: QuizComponentsText[] = [...supportedLanguages].map(
  (lang) => quizComponentsTexts[lang]
);

export default quizComponentsTexts;